### ISSUE TITLE
Unity 6000.5 compile errors: 3.4.0 references Sirenix/Odin types without dependency

### ISSUE THREAD

**Issue by wallstop** [wallstop/unity-helpers#275]
## Description

`com.wallstop-studios.unity-helpers@3.4.0` fails to compile in a Unity `6000.5.2f1` project because runtime sources reference Sirenix/Odin types that are not present in the project and are not resolved by the package manifest.

This was observed after resolving the package from the npm scoped registry, not from an embedded package folder.

## Environment

- Unity Editor: `6000.5.2f1`
- Package: `com.wallstop-studios.unity-helpers@3.4.0`
- Resolver/source: UPM registry, `https://registry.npmjs.org`
- Platform observed: Windows editor through Unity MCP

Manifest snippet from the consuming project:

```json
{
  "dependencies": {
    "com.unity.ai.assistant": "2.13.0-pre.2",
    "com.wallstop-studios.data-visualizer": "0.0.35-rc05.6",
    "com.wallstop-studios.dxmessaging": "3.2.0",
    "com.wallstop-studios.dxstate": "0.0.2",
    "com.wallstop-studios.unity-helpers": "3.4.0"
  },
  "scopedRegistries": [
    {
      "name": "NPM",
      "url": "https://registry.npmjs.org",
      "scopes": ["com.wallstop-studios"]
    }
  ]
}
```

Unity MCP package-state probe confirms registry resolution:

```text
UnityVersion=6000.5.2f1
com.wallstop-studios.unity-helpers version=3.4.0 source=Registry resolvedPath=D:\Code\DoxReloaded\Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f
EmbeddedWallstopFolders=<none>
```

## Compiler log excerpt

```text
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Tags\AttributeEffect.cs(17,11): error CS0246: The type or namespace name 'Sirenix' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Tags\AttributeEffect.cs(111,9): error CS0246: The type or namespace name 'SerializedScriptableObject' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Tags\AttributeEffect.cs(145,10): error CS0246: The type or namespace name 'ShowIfAttribute' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Tags\AttributeEffect.cs(145,10): error CS0246: The type or namespace name 'ShowIf' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Tags\AttributeEffect.cs(163,10): error CS0246: The type or namespace name 'ShowIfAttribute' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Tags\AttributeEffect.cs(163,10): error CS0246: The type or namespace name 'ShowIf' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Utils\RuntimeSingleton.cs(14,11): error CS0246: The type or namespace name 'Sirenix' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Utils\RuntimeSingleton.cs(41,9): error CS0246: The type or namespace name 'SerializedMonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Utils\ScriptableObjectSingleton.cs(15,11): error CS0246: The type or namespace name 'Sirenix' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.wallstop-studios.unity-helpers@ed8fe2701d2f\Runtime\Utils\ScriptableObjectSingleton.cs(52,9): error CS0246: The type or namespace name 'SerializedScriptableObject' could not be found (are you missing a using directive or an assembly reference?)
```

## Steps to reproduce

1. Open a Unity `6000.5.2f1` project without Odin Inspector/Sirenix assemblies installed.
2. Configure the `com.wallstop-studios` scoped registry to `https://registry.npmjs.org`.
3. Add `com.wallstop-studios.unity-helpers@3.4.0` to `Packages/manifest.json`.
4. Allow UPM to resolve packages and trigger script compilation.
5. Observe `CS0246` errors in `Runtime/Tags/AttributeEffect.cs`, `Runtime/Utils/RuntimeSingleton.cs`, and `Runtime/Utils/ScriptableObjectSingleton.cs`.

## Expected behavior

`unity-helpers@3.4.0` should compile in a project that installs the package through UPM, either by declaring/packaging the required dependency, making Odin/Sirenix integration optional, or guarding Odin-specific code behind an assembly define/version define.

## Actual behavior

Compilation fails because package runtime code references `Sirenix`, `SerializedScriptableObject`, `SerializedMonoBehaviour`, and `ShowIf`/`ShowIfAttribute` directly.

## Attempted local isolation

- Verified `Packages/com.wallstop-studios.unity-helpers` does not exist, so an embedded package is not overriding the registry package.
- Verified `Packages/packages-lock.json` resolves `com.wallstop-studios.unity-helpers` with `"source": "registry"` and `"url": "https://registry.npmjs.org"`.
- Queried Unity MCP `PackageInfo.GetAllRegisteredPackages()` and confirmed `source=Registry` for `com.wallstop-studios.unity-helpers@3.4.0`.
- Did not patch `Library/PackageCache`; this is package-owned source.

## Suggested direction

If Odin support is intended to be optional, move the Sirenix-backed base classes/attributes behind compile-time guards or assembly definition version defines. If Odin is required, publish/package metadata should make that dependency explicit enough that consumers do not get unresolved runtime symbols after UPM resolution.
